// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJsGHsqzlrXo6x_JWJlo2PwofddqUj6sY',
    appId: '1:962614466280:web:dd21e24b99faa434e01b5d',
    messagingSenderId: '962614466280',
    projectId: 'guardian-b7926',
    authDomain: 'guardian-b7926.firebaseapp.com',
    storageBucket: 'guardian-b7926.firebasestorage.app',
    measurementId: 'G-J8NRKLB0CK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1aWZGSkt72IAqrrG7MUljj8A7UHA8aQ',
    appId: '1:962614466280:android:e60fca1ddd47f78ee01b5d',
    messagingSenderId: '962614466280',
    projectId: 'guardian-b7926',
    storageBucket: 'guardian-b7926.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrzelrsNDEaBmz9IT-p7Y3UYjpic6HNg0',
    appId: '1:962614466280:ios:f7e9c083a1f1083be01b5d',
    messagingSenderId: '962614466280',
    projectId: 'guardian-b7926',
    storageBucket: 'guardian-b7926.firebasestorage.app',
    androidClientId: '962614466280-fvl44r23n5kpbqrn9shmen5729mmnfr3.apps.googleusercontent.com',
    iosClientId: '962614466280-57n2vppiknrr1q3b9rnsuudkqfqur8rk.apps.googleusercontent.com',
    iosBundleId: 'com.example.easyHelp',
  );
}
